### PR TITLE
Skip 2.2.1 update

### PR DESCRIPTION
**Pull request by Nickoriginal**
An attempt to let F-Droid to build and upload the latest release. Also bump NewPipe Extractor and some other libraries as well. If merged, tag the 2.2.2 release.

### CODE REVIEW

**Comment by nikhilCad** [comment]
Do you have the apk for this? I think the Github actions bot is broken too and can't find the latest apk anywhere

**Comment by Nickoriginal** [comment]
> Do you have the apk for this?

No, it runs into fatal error on building (flutter pub get)

> fatal: remote error:
The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
exit code: 128

This can be fixed by repository owner.
I'm trying to let at least F-Droid to build a new release with the latest important changes. You must wait.

**Comment by nikhilCad** [comment]
Project is abandoned, last commit 7 months ago. Alternative app I found - ViMusic, and "Music" by z-huang

**Comment by Nickoriginal** [comment]
I agree with you 👍

**Pull request closed without merging**
