### PR TITLE
Privacy.md

### PR DESCRIPTION
**Pull request by HarryHeights**
Here's the privacy policy I promised to create. Let me know what you think about it.

### CODE REVIEW

**Comment by deep-gaurav** [comment]
Thank You for all the work you've done, I'm in middle of exam days right now, so will take a few days to merge and add it in App Interface

**Comment by HarryHeights** [comment]
Alright @deep-gaurav. No qualms

**Comment by deep-gaurav** [comment]
Thank You, it has been merged and also added in app from version v1.1.5

**Comment by HarryHeights** [comment]
You are welcome.  Glad I could help. Would you like a contributor's guidelines? And maybe FAQs too.

**Comment by deep-gaurav** [comment]
App does need contributer guidelines, FAQs and even a simple help doc since some features are getting a little complicated to find.

Even readme needs updates, features written are not really relevant.

I'm planning to do some changes like adding AutoPlay (similar to YouTube) within a few days.

After major changes are done I can provide points which you can use to create document.

Thank You

**Comment by HarryHeights** [comment]
Alright. So in essence, you are saying I should pause on creating the proposed documents?

**Comment by deep-gaurav** [comment]
Yes for now, since they might need some editing soon

**Comment by deep-gaurav** [comment]
I'll create issues when ready and have you assigned if that's Okay with you?

**Comment by HarryHeights** [comment]
That's very okay by me.

**Pull request merged**
