### PR TITLE
Update for dependencies

### LINKED ISSUE #139: Fetch Error Can't load
on searching a song its giving me an error
IMG_20201102_094354

### PR DESCRIPTION
**Pull request by mmaenz**
as referenced in issue #134 

gradle to 6.5
newPipeExtractor to 0.20.8
okHttp to 4.9.0
changes in NewPipeDownloader  due to newPipeExtractor API changes
using google findbugs for @Nullable

Tested on Android 6.0.1 phone with `flutter run --release`. Search, fetch and play works like a charm. `flutter test` fails for unknown reason?? Don't know what the purpose of the test should be. 

Sorry it took so long, didn't have the time until now.

fixes #139

### CODE REVIEW

**Comment by mmaenz** [comment]
Sorry it took so long, didn't have the time until now.

Tested it on Blackberry Android 6.0.1 with flutter run --release. Search, fetch, play works. Should fix #139.
May you put it on f-droid?

Thanks a lot!

**Comment by mmaenz** [comment]
Youtube has changed json reply. PR doesn't work out of the box now. Newer version of NewPipeExtractor is needed and I'm on it but it's time consuming...
If someone don't mind I can make the apk and you can download and install by yourself instead of f-droid.

**Comment by deep-gaurav** [comment]
Hey, sorry for the late response, 
What is meant by doens't work out of box? Should I merge this PR?

**Comment by ShareASmile** [comment]
> What is meant by doens't work out of box? Should I merge this PR?

I think We Should wait for NewPipe extractor update from 0.20.8 to to latest 0.21.1 OR to (0.21.2 to be released in a day or two) in this PR by @mmaenz as youtube has changed json response & brought in new EU Cookie CONSENT  Page in the meantime 

Good to know that some development is being done to make app working again. Hopefully updating NewPipe Extractor to latest v0.21.1 would work fine & latest apk will be released soon here.
Kudos to Team for beautifully designed App.

**Comment by mmaenz** [comment]
invidious has stopped its service. Tried to update to https://invidious.snopyta.org but dart http client always returns 403 - Forbidden. I don't know why.

Found last host which is https://invidious.13ad.de
For now it is working on my phone!

**Comment by mmaenz** [comment]
You can approve and merge my changes...

**Comment by Yagueteiro** [comment]
@mmaenz I'm checking the new release but I can't seem to make it work. Every time I search a song I see this screen:
Screenshot_20210607-165540_MusicPiped
Tried switching multiple invidious apis without any change

**Comment by mmaenz** [comment]
Did you have MusicPiped installed before? I had to swipe (clear cache and data) the old version. Failed to load post is a problem with invidious. MusicPiped loads invidious link from database which needs to be purged.

But be aware!! This will delete all your cached files! I will release a new version with a more detailed error message soon.

**Comment by Yagueteiro** [comment]
Thanks, it works now! It was responding a 403 to all my requests. Chose a different URL from the invidious wiki and it works now

**Comment by deep-gaurav** [comment]
Thanks,

**Comment by deep-gaurav** [comment]
> Made release for [download](https://github.com/mmaenz/MusicPiped/releases/tag/2.1.7). Will be removed if f-droid is up to date.

Created release v2.2.0
F-Droid should create release soon.

**Comment by ShareASmile** [comment]
So far App hasn't been updated on Fdroid, any build  problems?

FDroid status build can be checked by this app:
https://codeberg.org/pstorch/F-Droid_Build_Status

**Comment by deep-gaurav** [comment]
> So far App hasn't been updated on Fdroid, any build  problems?
> 
> Edit: App has been updated to v2.2.0 on Fdroid. Maybe i spoke too soon.
> Thanks @mmaenz & deep-gaurav 
> 
> btw FDroid status build can be checked by this app:
> https://codeberg.org/pstorch/F-Droid_Build_Status
> Fdroid link:
> https://f-droid.org/en/packages/de.storchp.fdroidbuildstatus/

It's available now on F-Droid

**Pull request merged**
