### PR TITLE
Add a download feature to MusicPiped app

### PR DESCRIPTION
**Pull request by chrisbarth01**
#### Components
The component I want to suggest is a download button that will aid users (who wish) to download any music they want. 

---

#### Proposal Description
Though I understand that the MusicPiped app is a *music streaming app* but there are certain users like me who see certain songs and wish they had it downloaded on their device. I propose that an option to download any music should be added. This feature will be optional; only users who want to download a music will use it. This feature can be added as a download symbol on the downside of each and every music that appears on the search result. I like the fact that this same team made the NewPipe legacy app and I believe that this feature which I request can be added (since it's the same NewPipe team).

---

#### Mockups / Examples
Below is a mock-up of my suggestion, it is an edited screenshot;
PicsArt_05-04-03 08 20

---

#### Benefits
- If this feature is added, users will be able to also download any music which they want to. 

---

#### Conclusion 
This is quite important since the app streams its music from YouTube and it's obvious that there are many YouTube songs which users will definitely want downloaded on their device....

### CODE REVIEW

**Comment by deep-gaurav** [comment]
I guess it's not a pull request but a Feature Request, kindly open issue for feature request instead
Although it's already open in #23

The current problem with adding a download option is that app is still available on Playstore and a large amount of userbase are dependent on play store for updates. Play store will remove the app if a download option is added, it's not hard to implement but a separate version will need to be made and maintaining two versions take time which I currently lack.

That being said a share option will be provided in next version, if you've newpipe installed clicking on share and choosing newpipe should present you with download option in newpipe.

Also for clarification this app is not made by NewPipeTeam,
I'm just using NewPipe Extractor since it's open source to fetch streams from YouTube

**Comment by chrisbarth01** [comment]
Hello @deep-gaurav I'll open the feature request. However, the #23 is a question..... And he was answered no. Can I open a new feature request since #23 didn't make a direct request

**Comment by chrisbarth01** [comment]
I have created the feature request and I remove the NewPipe team statement. Thank you

**Comment by ArmeF97** [comment]
#23 is not a question, is a feature request, as title suggest. And it's still open

**Comment by chrisbarth01** [comment]
OK then.

**Pull request closed without merging**
